version: '2.2'
services:
  node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.1
    container_name: node1
    environment:
      - node.name=node1
      - discovery.seed_hosts=node2,node3
      - cluster.initial_master_nodes=node1,node2,node3
      - cluster.name=eoc-06-cluster
      - bootstrap.memory_lock=true
      - node.attr.AZ=earth
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - node1-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.1
    container_name: node2
    environment:
      - node.name=node2
      - discovery.seed_hosts=node1,node3
      - cluster.initial_master_nodes=node1,node2,node3
      - cluster.name=eoc-06-cluster
      - bootstrap.memory_lock=true
      - node.attr.AZ=earth
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - node2-data:/usr/share/elasticsearch/data
    networks:
      - elastic
  node3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.1
    container_name: node3
    environment:
      - node.name=node3
      - discovery.seed_hosts=node1,node2
      - cluster.initial_master_nodes=node1,node2,node3
      - cluster.name=eoc-06-cluster
      - bootstrap.memory_lock=true
      - node.attr.AZ=mars
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - node3-data:/usr/share/elasticsearch/data
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    links:
      - node3:elasticsearch
    networks:
      - elastic
volumes:
  node1-data:
    driver: local
  node2-data:
    driver: local
  node3-data:
    driver: local

networks:
  elastic:
